CREATE TABLE reminders.reminders (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    uid VARCHAR(64) UNIQUE NOT NULL,
    
    message VARCHAR(2000) NOT NULL,
    channel BIGINT UNSIGNED NOT NULL,
    `time` INT UNSIGNED DEFAULT 0 NOT NULL,
    position INT UNSIGNED DEFAULT NULL,
    webhook VARCHAR(256),
    enabled BOOLEAN DEFAULT 1 NOT NULL,

    avatar VARCHAR(512) DEFAULT "https://raw.githubusercontent.com/reminder-bot/logos/master/Remind_Me_Bot_Logo_PPic.jpg" NOT NULL,
    username VARCHAR(32) DEFAULT "Reminder" NOT NULL,
    embed MEDIUMINT UNSIGNED,

    method TEXT,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.intervals (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,

    reminder INT UNSIGNED NOT NULL,
    period INT UNSIGNED NOT NULL,
    position TINYINT UNSIGNED NOT NULL DEFAULT 0,

    CONSTRAINT reminder_period_cx
    FOREIGN KEY reminder_period_fk (reminder)
    REFERENCES reminders (id)
    ON DELETE CASCADE,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.servers (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    server BIGINT UNSIGNED UNIQUE NOT NULL,

    prefix VARCHAR(5) DEFAULT "$" NOT NULL,
    timezone VARCHAR(32) DEFAULT "UTC" NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.users (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    user BIGINT UNSIGNED UNIQUE NOT NULL,

    language VARCHAR(2) DEFAULT "EN" NOT NULL,
    timezone VARCHAR(32),
    allowed_dm BOOLEAN DEFAULT 1 NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.todos (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    owner BIGINT UNSIGNED NOT NULL,
    value TEXT,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.blacklists (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    channel BIGINT UNSIGNED UNIQUE NOT NULL,
    server BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.roles (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    role BIGINT UNSIGNED UNIQUE NOT NULL,
    server BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.timers (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    start_time INT UNSIGNED DEFAULT (UNIX_TIMESTAMP()) NOT NULL,
    name VARCHAR(32) NOT NULL,
    owner BIGINT UNSIGNED NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.nudge_channels (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    channel BIGINT UNSIGNED UNIQUE NOT NULL,
    `time` INT NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE reminders.languages (
    id SMALLINT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL,
    name VARCHAR(20) NOT NULL,
    code VARCHAR(2) NOT NULL,

    PRIMARY KEY (id)
);
-- MUST RUN to_database.py TO FORM STRING STORES